### ISSUE TITLE
Question - arm and amd64

### ISSUE THREAD

**Issue by joeblew99** [ubuntu-core/snapcraft#271]
I need to package for arm and amd64.

Can I do this with the current state of the code ?

I will be packaging my own code which is written in golang, so zero dependencies.
But my code depends on postresql and possibly rethinkdb.
Also I am wondering where I can search for packages on the web. I know from the CLI I can search for them, but the result list is mostly stuff people don't need. So I am wondering if there are other repos ?

Also for these dependencies like postresql, I guess I can reference them in my own SNAP as debs ?
But if I need to install 2 different versions of postresql ; a different version for each of my apps, can the system handle that currently.

Thanks in advance ...

I tried to convert this into a question on launch pad but it would not let me.

Joe

**Comment by sergiusens** [comment]
Thanks for sharing, please read issue #100 

For specific questions, please refer to the [snappy-app-devel](https://lists.ubuntu.com/mailman/listinfo/snappy-app-devel) mailing list for the knowledge to be spread amongst many.

Thanks.
