### ISSUE TITLE
How to install bonescript on snappy ubuntu core?

### ISSUE THREAD

**Issue by MarinRadmilovic** [ubuntu-core/snapcraft#390]
Snappy ubuntu core is perfect OS for IoT, and Bonescript is prefect library for BeagleBone Black. Please is someone know how to install and use Bonescript on Snappy ubuntu core. Does it need to be self application, or just node package installed globally in application enviroment? It would be great to have some example.

**Comment by kyrofa** [comment]
Thanks for the question @MarinRadmilovic, but please see issue #100. Please post your question to the [snappy-app-devel](https://lists.ubuntu.com/mailman/listinfo/snappy-app-devel) mailing list.
