### ISSUE TITLE
Logging out from the run environment produces a traceback

### ISSUE THREAD

**Issue by sergiusens** [ubuntu-core/snapcraft#40]
(amd64)ubuntu@localhost:~$ logout
Connection to localhost closed.
Traceback (most recent call last):
  File "/usr/bin/snapcraft", line 33, in <module>
    snapcraft.main.main()
  File "/usr/lib/python3/dist-packages/snapcraft/main.py", line 80, in main
    args.func(args)
  File "/usr/lib/python3/dist-packages/snapcraft/cmds.py", line 228, in run
    preexec_fn=os.setsid)
  File "/usr/lib/python3/dist-packages/snapcraft/cmds.py", line 343, in _check_call
    return subprocess.check_call(args, **kwargs)
  File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ssh', '-i', '/home/daniel/.ssh/ubuntudevice_0149BDCB0C009017_id_rsa', '-oStrictHostKeyChecking=no', '-oUserKnownHostsFile=/tmp/tmpcaocvoj7', '-oKbdInteractiveAuthentication=no', '-p', '8022', 'ubuntu@localhost']' returned non-zero exit status 1
daniel@daydream:~/dev/apps/bwm-ng.snap$

Launchpad Details: [#LP1499242](https://bugs.launchpad.net/bugs/1499242) Daniel Holbach - 2015-09-24 06:05:27 -0300

**Comment by sergiusens** [comment]
I don't see this on `wily`, on what system does this happen @dholbach ?

**Comment by plars** [comment]
I can explain this. If the last command executed in the session exits non-zero, then check_call will pick up on that and raise the exception.  It looks horrible to the user, but in reality they probably just hit ctrl-c or something in their last command.  I've proposed a small fix to change the _check_call() to _call and avoid this.
