### ISSUE TITLE
qml plugin: make it combinable with apps which use other build systems to install their files

### ISSUE THREAD

**Issue by sergiusens** [ubuntu-core/snapcraft#46]
Alan put together a branch which builds lp:music-app using the cmake plugin (https://bazaar.launchpad.net/~popey/+junk/music-app-snap/view/head:/snapcraft.yaml). This works just fine, but a lot of dependencies are not bundled, so I tried to use the qml plugin. This works fine, but the music-app expects some files in the right place (like translations), for which it uses cmake.

Trying to use both (snapcraft.yaml snippet below), you run into the problem that both try to install the same files (the qml plugin installs * - https://bazaar.launchpad.net/~snappy-dev/snapcraft/core/view/head:/snapcraft/plugins/qml.py#L67), which breaks the build. Maybe the qml plugin could be more selective in what exactly it tries to bundle?

parts:
  music-build:
    plugin: cmake
    source: https://launchpad.net/music-app
    source-type: bzr
    snap: 
      - icon.png
  music-app:
    plugin: music-qml
    after: music-build

Launchpad Details: [#LP1510008](https://bugs.launchpad.net/bugs/1510008) Daniel Holbach - 2015-10-26 06:29:45 -0300

**Comment by sergiusens** [comment]
I'm a bit confused. If snapcraft sees that two parts have the same file in the same location it won't have an issue with that. So it wouldn't matter whether all the packages were installed or not.

Also, the snapcraft.yaml snippet here includes a custom plugin, which you should attach, but also shouldn't be needed. The version in the repo doesn't have the custom plugin.

Last comment, this should really be in the repo for the music app. There's no reason to make another repository just for the snapcraft file.

Launchpad Details: [#LPC](https://bugs.launchpad.net/snapcraft/+bug/1510008/comments/1) Ted Gould - 2015-10-26 10:27:39 -0300

**Comment by sergiusens** [comment]
Ok... should something like this work lp:~dholbach/music-app/initial-snapcraft-work?

Launchpad Details: [#LPC](https://bugs.launchpad.net/snapcraft/+bug/1510008/comments/2) Daniel Holbach - 2015-10-26 10:53:43 -0300

**Comment by ted-gould** [comment]
@dholbach I think that you want them the other way around. You want your cmake to build after the qml plugin installs all of the libraries.

**Comment by ted-gould** [comment]
Closing issue for now. We can reopen if the cmake change doesn't fix it.
