### ISSUE TITLE
putting two maven parts in a snapcraft fails

### ISSUE THREAD

**Issue by sergiusens** [ubuntu-core/snapcraft#7]
Put two maven projects in one snapcraft.yaml and the second fails with a directory already exists. Probably the JDK but the directory mentioned in the error is not the real directory. 

  javamqtt:
        plugin: maven-project
        source: git://git.eclipse.org/gitroot/paho/org.eclipse.paho.mqtt.java.git

    javascriptmqtt:
        plugin: maven-project
        source: git clone http://git.eclipse.org/gitroot/paho/org.eclipse.paho.mqtt.javascript.git

    args.func(args)
  File "/home/maarten/icebreaker/snapcraft/snapcraft/cmds.py", line 331, in cmd
    if not getattr(part, cmd)(force=force):
  File "/home/maarten/icebreaker/snapcraft/snapcraft/plugin.py", line 205, in build
    self.makedirs()
  File "/home/maarten/icebreaker/snapcraft/snapcraft/plugin.py", line 148, in makedirs
    os.makedirs(d, exist_ok=True)
  File "/usr/lib/python3.4/os.py", line 237, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/home/maarten/icebreaker/snapcraft/examples/aws-iot/parts/javascriptmqtt/build'

Launchpad Details: [#LP1502030](https://bugs.launchpad.net/bugs/1502030) maarten ectors - 2015-10-02 05:05:19 -0300

**Comment by ted-gould** [comment]
I built a small example with two maven projects and it built fine. I tried with paho and it seems maven can't find the jar files that are built here. So closing until we get a snapcraft.yaml that builds, but not with two maven projects, otherwise I think this was fixed by the build/src separation.
